### ISSUE TITLE
Pass backend values as module variable (e.g. local, s3 or gcs)

### ISSUE THREAD

**Issue by eistrati** [TerraHubCorp/terraform-aws-landing-zone#110]
## Describe the Feature
Pass backend values as module variable (e.g. local, s3 or gcs)

## Expected Behavior
```hcl
module "landing_zone" {
  source    = "TerraHubCorp/landing-zone/aws"
  version   = "0.1.3"
  root_path = path.module
  landing_zone_providers  = var.landing_zone_providers
  landing_zone_components = var.landing_zone_components
  landing_zone_backend = var.landing_zone_backend
}
```
> NOTE: `landing_zone_backend` should be optional. If not defined, assume `local`.

Default value must be `local` and would be defined like this:
```hcl
landing_zone_backend = {
  backend = "local"
  path_prefix = "/tmp/.terrahub/landing_zone/"
}
```
> NOTE: `path_prefix` should be prefixed to `path` argument in terraform `local` backend.

Most common value will be `s3` and would be defined like this:
```hcl
landing_zone_backend = {
  backend = "s3"
  bucket = "data-lake-terrahub-us-east-1"
  region = "us-east-1"
  key_prefix = "terraform/terrahub/api/"
  workspace_key_prefix = "terraform_workspaces"
}
```
> NOTE: `key_prefix` should be prefixed to `key` argument in terraform `s3` backend.

Least common value will be `gcs` and would be defined like this:
```hcl
landing_zone_backend = {
  backend = "gcs"
  bucket = "data-lake-terrahub-us-east4"
  key_prefix = "terraform/terrahub/api"
}
```
> NOTE: `key_prefix` should be prefixed to `prefix` argument in terraform `gcs` backend.

**Comment by euliancom** [comment]
> NOTE: `landing_zone_backend` should be optional and we will use the same parameters like in the terraform.

Default value must be `local` and would be defined like this:
```hcl
landing_zone_backend = {
  backend = "local"
  path = "/tmp/.terrahub/landing_zone/"
}
```

Most common value will be `s3` and would be defined like this:
```hcl
landing_zone_backend = {
  backend = "s3"
  bucket = "data-lake-terrahub-us-east-1"
  region = "us-east-1"
  key = "terraform/terrahub/api/"
  workspace_key_prefix = "terraform_workspaces"
}
```

Least common value will be `gcs` and would be defined like this:
```hcl
landing_zone_backend = {
  backend = "gcs"
  bucket = "data-lake-terrahub-us-east4"
  prefix = "terraform/terrahub/api"
}
```

**Comment by eistrati** [comment]
Done
