### ISSUE TITLE
Create aws_organizations_account into specified organizational_unit

### ISSUE THREAD

**Issue by jaredvonhalle** [TerraHubCorp/terraform-aws-landing-zone#142]
## Describe the Bug
Currently, the `landing_zone_organization_accounts` component defaults to using the root organization as the `parent_id`.

## Expected Behavior
Allow an `organization_account` to be created within a specific organizational unit. 

An alternative would be to expose a component for the "MoveAccount" AWS command. Though this functionality does not currently exist as an AWS Terraform resource.

**Comment by eistrati** [comment]
@jaredvonhalle thanks for reporting this issue! we are considering your suggestion and will get back to this thread shortly after...

**Comment by eistrati** [comment]
@jaredvonhalle we have tried to resolve this issue by introducing a completely new component [landing_zone_organization_accounts_non_master](https://github.com/TerraHubCorp/terraform-aws-landing-zone/tree/dev/components/landing_zone_organization_accounts_non_master) that can be used as a replacement for [landing_zone_organization_accounts](https://github.com/TerraHubCorp/terraform-aws-landing-zone/tree/dev/components/landing_zone_organization_accounts) in your use case. Please let us know if this is helpful. Any feedback is more than welcomed!

**Comment by jaredvonhalle** [comment]
@eistrati Thank you for getting to this so quickly, the solution looks great!

**Comment by eistrati** [comment]
Thank you for reporting this issue and thank you for using this module. I will close this issue now, but feel free to open others as you come across other issues.
