### ISSUE TITLE
[question] Will this module support to set up landing zone in two aws accounts?

### ISSUE THREAD

**Issue by ozbillwang** [TerraHubCorp/terraform-aws-landing-zone#169]
I have only 2 aws accounts, could I used this module to test landing zone? One for master account, where I create landing zone stack, and the other account will be used as core/application accounts.

With aws landing zone cloudformation template, it asks for another 3 root mailboxes (that's totally 4 aws accounts needed). I can't give same mailboxes to skip the error

```
Shared Services Account Email Address
Log Archive Account Email Address
Security Account Email Address
```

In this terraform module's statement: `By removing the need for access to AWS root account(s)`

Does it mean I can have a try?

**Comment by eistrati** [comment]
@ozbillwang Short answer - yes. Longer answer - our module doesn't enforce the number of AWS accounts you must use. Therefore, if you define only 2 providers in `landing_zone_providers` variable, you will be able to use this terraform module only on 2 accounts setup without any limitations.
